/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}.about'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}.contact'
import { Route as Char123LocaleChar125LegalRouteImport } from './routes/{-$locale}.legal'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}.privacy'
import { Route as Char123LocaleChar125ServicesRouteImport } from './routes/{-$locale}.services'
import { Route as Char123LocaleChar125WorkIndexRouteImport } from './routes/{-$locale}.work.index'
import { Route as Char123LocaleChar125WorkSlugRouteImport } from './routes/{-$locale}.work.$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LegalRoute =
  Char123LocaleChar125LegalRouteImport.update({
    id: '/legal',
    path: '/legal',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesRoute =
  Char123LocaleChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkIndexRoute =
  Char123LocaleChar125WorkIndexRouteImport.update({
    id: '/work/',
    path: '/work/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkSlugRoute =
  Char123LocaleChar125WorkSlugRouteImport.update({
    id: '/work/$slug',
    path: '/work/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/work/$slug': typeof Char123LocaleChar125WorkSlugRoute
  '/{-$locale}/work/': typeof Char123LocaleChar125WorkIndexRoute
}
export interface FileRoutesByTo {
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/work/$slug': typeof Char123LocaleChar125WorkSlugRoute
  '/{-$locale}/work': typeof Char123LocaleChar125WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/legal': typeof Char123LocaleChar125LegalRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/work/$slug': typeof Char123LocaleChar125WorkSlugRoute
  '/{-$locale}/work/': typeof Char123LocaleChar125WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/api/analytics'
    | '/api/health'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/legal'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/work/$slug'
    | '/{-$locale}/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/analytics'
    | '/api/health'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/legal'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}'
    | '/{-$locale}/work/$slug'
    | '/{-$locale}/work'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/api/analytics'
    | '/api/health'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/legal'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}/'
    | '/{-$locale}/work/$slug'
    | '/{-$locale}/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/legal': {
      id: '/{-$locale}/legal'
      path: '/legal'
      fullPath: '/{-$locale}/legal'
      preLoaderRoute: typeof Char123LocaleChar125LegalRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services': {
      id: '/{-$locale}/services'
      path: '/services'
      fullPath: '/{-$locale}/services'
      preLoaderRoute: typeof Char123LocaleChar125ServicesRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/work/': {
      id: '/{-$locale}/work/'
      path: '/work'
      fullPath: '/{-$locale}/work/'
      preLoaderRoute: typeof Char123LocaleChar125WorkIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/work/$slug': {
      id: '/{-$locale}/work/$slug'
      path: '/work/$slug'
      fullPath: '/{-$locale}/work/$slug'
      preLoaderRoute: typeof Char123LocaleChar125WorkSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125LegalRoute: typeof Char123LocaleChar125LegalRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125ServicesRoute: typeof Char123LocaleChar125ServicesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125WorkSlugRoute: typeof Char123LocaleChar125WorkSlugRoute
  Char123LocaleChar125WorkIndexRoute: typeof Char123LocaleChar125WorkIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125LegalRoute: Char123LocaleChar125LegalRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125ServicesRoute: Char123LocaleChar125ServicesRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125WorkSlugRoute: Char123LocaleChar125WorkSlugRoute,
  Char123LocaleChar125WorkIndexRoute: Char123LocaleChar125WorkIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
